name: Formatter
on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Formatter:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Installing Libraries
        run: |
          haxelib install formatter --quiet

      - name: Formatting
        run: haxelib run formatter -s ./source

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: formattedSource
          path: |
            source
            !**/.gitignore
            hxformat.json
          if-no-files-found: error
  Publisher:
    needs: Formatter
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ github.head_ref }}

      - name: Delete source
        run: rm -rf source

      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          path: .
          name: formattedSource

      - name: Push to GitHub
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "Formatted the source files."
